### ISSUE TITLE
Allow the launcher to work with Java SE 24

### ISSUE THREAD

**Issue by jamezp** [wildfly/wildfly-launcher#6]
In Java SE 24 the [security manager has been disabled](https://openjdk.org/jeps/486). We see failures on Java SE 24 due to the launcher passing `-Djava.security.manager=allow`. With JEP 486, this property throws an error.

```
Error occurred during initialization of VM
java.lang.Error: A command line option has attempted to allow or enable the Security Manager. Enabling a Security Manager is not supported.
	at java.lang.System.initPhase3(java.base@24-beta/System.java:2070)
```

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the StandaloneCommandBuilder to check for Java version before adding the security manager property. For Java versions 24 and above, we skip adding the '-Djava.security.manager=allow' argument to prevent the error in Java SE 24.

You can review changes in this commit: https://github.com/lattaai13/wildfly-wildfly-launcher-6/commit/1b2e9079fefd3d13a08f0529ffa795743cb88e1a.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jamezp** [comment]
Part of this issue is in WildFly itself, see [WFCORE-7059](https://issues.redhat.com/browse/WFCORE-7059).
